version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: uno-backend-dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: ./mvnw spring-boot:run -Dspring.devtools.restart.enabled=true
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: uno-frontend-dev
    depends_on:
     - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run start